tracking down "broken now" problem maybe

diff --git a/.github/workflows/gold.yml b/.github/workflows/gold.yml
--- a/.github/workflows/gold.yml
+++ b/.github/workflows/gold.yml
@@ -20,21 +20,21 @@ jobs:
 #     - name: Action, branch, and repo information.
 #       run: printf "$SHOW_ACTION\n$SHOW_BRANCH\n$SHOW_BNAME\n$SHOW_SHA\n"
 
-  func_fail_1m:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check out repository code
-      uses: actions/checkout@v2
-    - name: Run the test
-      run: test/copy_of_garnet_tests_test_app.sh --fail $BRANCH_NAME 4x2 apps/pointwise && exit 13 || echo FAILED SUCCESSFULLY
-
-  gold_fail_2m:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check out repository code
-      uses: actions/checkout@v2
-    - name: Run the test
-      run: test/genesis-ci.sh --fail $BRANCH_NAME && exit 13 || echo FAILED SUCCESSFULLY
+#   func_fail_1m:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Check out repository code
+#       uses: actions/checkout@v2
+#     - name: Run the test
+#       run: test/copy_of_garnet_tests_test_app.sh --fail $BRANCH_NAME 4x2 apps/pointwise && exit 13 || echo FAILED SUCCESSFULLY
+# 
+#   gold_fail_2m:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Check out repository code
+#       uses: actions/checkout@v2
+#     - name: Run the test
+#       run: test/genesis-ci.sh --fail $BRANCH_NAME && exit 13 || echo FAILED SUCCESSFULLY
 
   gold_pass_3m:
     runs-on: ubuntu-latest
@@ -44,10 +44,10 @@ jobs:
     - name: Run the test
       run: test/genesis-ci.sh $BRANCH_NAME
 
-  func_pass_6m:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check out repository code
-      uses: actions/checkout@v2
-    - name: Run the test
-      run: test/copy_of_garnet_tests_test_app.sh $BRANCH_NAME 4x2 apps/pointwise
+#   func_pass_6m:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Check out repository code
+#       uses: actions/checkout@v2
+#     - name: Run the test
+#       run: test/copy_of_garnet_tests_test_app.sh $BRANCH_NAME 4x2 apps/pointwise
